version: '{build}'

cache:
- x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z
- i686-4.9.2-release-win32-dwarf-rt_v4-rev4.7z

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
  allow_failures:
    - platform: x64
    - platform: x86

environment:
  matrix:
    - MINGW_DIR: mingw64
      MINGW_URL: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/4.9.2/threads-win32/seh/x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z/download
      MINGW_ARCHIVE: x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z
      platform: x64
    - MINGW_DIR: mingw32
      MINGW_URL: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/4.9.2/threads-win32/dwarf/i686-4.9.2-release-win32-dwarf-rt_v4-rev4.7z/download
      MINGW_ARCHIVE: i686-4.9.2-release-win32-dwarf-rt_v4-rev4.7z
      platform: x86

install:
  - IF not exist "%MINGW_ARCHIVE%" appveyor DownloadFile "%MINGW_URL%" -FileName "%MINGW_ARCHIVE%"
  - 7z x -y "%MINGW_ARCHIVE%" > nul
  - SET PATH=%CD%\%MINGW_DIR%\bin;%CD%\Nim\bin;%PATH%
  - git clone -b nimbus https://github.com/status-im/Nim.git %CD%\Nim
  - cd %CD%\Nim
  - git clone --depth 1 https://github.com/status-im/csources
  - cd csources
  - IF "%PLATFORM%" == "x64" ( build64.bat ) else ( build.bat )
  - cd ..
  - bin\nim c koch
  - koch boot -d:release
  - cd C:\projects\nimcrypto

build_script:
  - cd tests
  - nim c testblowfish.nim
  - nim c testtwofish.nim
  - nim c testrijndael.nim
  - nim c testsha2.nim
  - nim c testkeccak.nim
  - nim c testripemd.nim
  - nim c testhmac.nim
  - nim c testbcmode.nim
test_script:
  - testblowfish
  - testtwofish
  - testrijndael
  - testsha2
  - testkeccak
  - testripemd
  - testhmac
  - testbcmode

deploy: off
